### ISSUE TITLE
WAMP clients are hanging waiting for response from server

### ISSUE THREAD

**Issue by haizaar** [KSDaemon/wiola#15] opened 2018-09-06 04:51 UTC
Good day,

I'm trying to configure minimum Wiola setup and failing to do that.

I've installed Wiola in Docker, basing on openresty image and mounting nginx config from the host in runtime. Redis runs as container as well and is linked to the wiola container.

The problem is that my minimal wamp client just hangs expecting the response (see the strace log below). The nginx logs show nothing beyond
```
... "GET /ws HTTP/1.1" 101 0 "-" "AutobahnPython/18.8.1" "-" 0.000 - .
```

Here is my [nginx.conf](https://gist.github.com/haizaar/208e4c63954db1cbc3aa1de4b8e5951f#file-nginx-conf). Can you please assist?

### Reproduction
* Download/unpack files from the [gist](https://gist.github.com/haizaar/208e4c63954db1cbc3aa1de4b8e5951f) and change dir to it.
* Build the docker image: `docker build -t wiola .`
* Start redis container: `sh ./start-redis.sh`
* Start wiola container: `sh ./start-wiola.sh`
* Now try to connect with a WAMP client. You can use sample `client.py` from the same gist (it requires Python 3.5+ with Autobahn|Python installed. Tell me if you need help with Python venv)

Here is the strace log:
```
sendto(6, "GET /ws HTTP/1.1\r\nUser-Agent: Au"..., 494, 0, NULL, 0) = 494
epoll_ctl(3, EPOLL_CTL_ADD, 6, {EPOLLIN, {u32=6, u64=8589934598}}) = 0
epoll_wait(3, [{EPOLLIN, {u32=6, u64=8589934598}}], 2, 0) = 1
mmap(NULL, 266240, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f75644bc000
recvfrom(6, "HTTP/1.1 101 Switching Protocols"..., 262144, 0, NULL, NULL) = 232
mremap(0x7f75644bc000, 266240, 4096, MREMAP_MAYMOVE) = 0x7f75644bc000
epoll_wait(3, [{EPOLLIN, {u32=6, u64=8589934598}}], 2, 0) = 1
mmap(NULL, 266240, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f756447b000
recvfrom(6, "", 262144, 0, NULL, NULL)  = 0
mremap(0x7f756447b000, 266240, 4096, MREMAP_MAYMOVE) = 0x7f756447b000
epoll_ctl(3, EPOLL_CTL_DEL, 6, 0x7ffd86fa16d0) = 0
munmap(0x7f756447b000, 4096)            = 0
fstat(5, {st_mode=S_IFSOCK|0777, st_size=0, ...}) = 0
fcntl(5, F_GETFL)                       = 0x802 (flags O_RDWR|O_NONBLOCK)
rt_sigaction(SIGTERM, {0x667570, [], SA_RESTORER, 0x7f756783c390}, {SIG_DFL, [], 0}, 8) = 0
rt_sigaction(SIGTERM, NULL, {0x667570, [], SA_RESTORER, 0x7f756783c390}, 8) = 0
rt_sigaction(SIGTERM, {0x667570, [], SA_RESTORER|SA_RESTART, 0x7f75669434b0}, NULL, 8) = 0
epoll_wait(3, [], 1, 0)                 = 0
close(6)                                = 0
epoll_wait(3, [], 1, 0)                 = 0
epoll_wait(3, 
```

**Comment by KSDaemon** [comment] 2018-09-12 12:05
Hi! 
Well, i’m still on vacation. Can this wait for some days? I can have a look next week. 
Anyway, it’s hard to help using only phone and very bad internet connection... 

Всего наилучшего!
Константин Буркалев

**Comment by haizaar** [comment] 2018-09-12 12:12
Sure!
Thanks for following up!

**Comment by KSDaemon** [comment] 2018-09-19 13:18
Hi! I quickly look into you gist. Well, first of all:  you try to connect to `clarity` realm, but in Wiola cfg there is only `realm1` :)

**Comment by KSDaemon** [comment] 2018-09-19 14:35
Next, what i see is: `Failed to create a wiola instance: no resolver defined to resolve "redis"`

**Comment by KSDaemon** [comment] 2018-09-19 14:37
So, i think there is some misconfiguration in docker resolvers. I'm not a big expert in docker, but i don't see any services defined in Dockerfile for wiola

**Comment by haizaar** [comment] 2018-09-21 08:53
Oh, sorry for the obvious glitches (nginx+DNS = headache).

I've updated gist with the new configuration - now running the containers on the same network so that I can connect to redis through 127.0.0.1. And fixed the realm obviously.

Now it works... for the first 15 seconds and then hits `WebSocket ping timeout` (each message below is printed once a second):
```
Join: SessionDetails(realm=<realm1>, session=7007047066812527, authid=<None>, authrole=<None>, authmethod=None, authprovider=None, authextra=None, resumed=None, resumable=None, resume_token=None)
publish: com.myapp.hello 0
publish: com.myapp.hello 1
publish: com.myapp.hello 2
publish: com.myapp.hello 3
publish: com.myapp.hello 4
publish: com.myapp.hello 5
publish: com.myapp.hello 6
publish: com.myapp.hello 7
publish: com.myapp.hello 8
publish: com.myapp.hello 9
publish: com.myapp.hello 10
publish: com.myapp.hello 11
publish: com.myapp.hello 12
publish: com.myapp.hello 13
publish: com.myapp.hello 14
2018-09-21T18:41:52 dropping connection to peer tcp:127.0.0.1:8080 with abort=True: WebSocket ping timeout (peer did not respond with pong in time)
2018-09-21T18:41:52 session closed with reason wamp.close.transport_lost [WAMP transport was lost without closing the session before]
publish: com.myapp.hello 15
2018-09-21T18:41:53 Task exception was never retrieved
future: <Task finished coro=<Component.onJoin() done, defined at client.py:7> exception=TransportLost()>
Traceback (most recent call last):
  File "client.py", line 15, in onJoin
    self.publish("com.myapp.hello", counter)
  File "/home/python/site-packages/autobahn/wamp/protocol.py", line 1289, in publish
    raise exception.TransportLost()
autobahn.wamp.exception.TransportLost
```

Any ideas?

P.S. Where did you see that resolver error? I even tried raising nginx error log level to debug, and  still didn't find it.

**Comment by KSDaemon** [comment] 2018-09-21 11:56
Hm... I think there is some trouble with websocket ping/pong.....
I'm having some problems with running ur python client... May be you can help me:
```
kostik@KOsTIK:~/Downloads/wiola-test/> python3 --version                                                                                   [14:51] cmd#8482
Python 3.7.0
kostik@KOsTIK:~/Downloads/wiola-test/> python3 client.py                                                                                   [14:54] cmd#8483
Traceback (most recent call last):
  File "client.py", line 2, in <module>
    from autobahn.asyncio.wamp import ApplicationSession, ApplicationRunner
  File "/usr/local/lib/python3.7/site-packages/autobahn/asyncio/__init__.py", line 36, in <module>
    from autobahn.asyncio.websocket import \
  File "/usr/local/lib/python3.7/site-packages/autobahn/asyncio/websocket.py", line 52
    ensure_future = asyncio.async
                                ^
SyntaxError: invalid syntax
```

```
kostik@KOsTIK:~/Downloads/wiola-test/!> python --version                                                                                   [14:54] cmd#8484
Python 2.7.15
kostik@KOsTIK:~/Downloads/wiola-test/> python client.py                                                                                    [14:54] cmd#8485
  File "client.py", line 7
    async def onJoin(self, details):
            ^
SyntaxError: invalid syntax
```

To see errors i've remapped some wiola files from repo/src (which include debug printing, not production) and set nginx log level to DEBUG like so:
```
exec docker run \
    --rm \
    -ti \
    --name=wiola \
    --net container:redis \
    --volume $PWD/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf \
    --volume $PWD/ws-handler.lua:/usr/local/openresty/luajit/share/lua/5.1/wiola/ws-handler.lua \
    --volume $PWD/wiola.lua:/usr/local/openresty/luajit/share/lua/5.1/wiola/wiola.lua \
    wiola $@
```

**Comment by haizaar** [comment] 2018-09-21 12:04
I'm not near laptop, but it seems like your autobahn is a bit old - "async"
is a keyword in 3.7. AFAIR, I run it in Python 3.7 as well, but you can try
Python 3.6 if you feel like or wait till I provide some details.

Thanks again for looking into this.

**Comment by KSDaemon** [comment] 2018-09-21 12:15
Ough thanks! I've reinstalled authobahn and now it works and i can reproduce this case. I'll debug it!

**Comment by KSDaemon** [comment] 2018-09-21 12:56
Ahah))) 
As i see, autobahn client sends `pong` frames, not `ping` one :) So Wiola just ignores them. AFAIK, as defined in RFC 6455 aka Websocket, any peer can send `ping` frame and other peer MUST reply with `pong`.

```
2018/09/21 15:48:22 [debug] [lua] redis.lua:404: addSessionToRealm(): No realm realm1 found. Creating...
2018/09/21 15:48:22 [debug] [lua] redis.lua:823: registerMetaRpc(): Registering Meta RPCs in realm: realm1
2018/09/21 15:48:22 [debug] [lua] ws-handler.lua:91: Got data for client. DataType is text. Sending...
2018/09/21 15:48:22 [debug] [lua] ws-handler.lua:112: Received WS Frame. Type is text
2018/09/21 15:48:22 [debug] [lua] ws-handler.lua:150: Received text data: [64,1,{},"com.myapp.ping"]
2018/09/21 15:48:22 [debug] [lua] ws-handler.lua:91: Got data for client. DataType is text. Sending...
2018/09/21 15:48:22 [debug] [lua] ws-handler.lua:112: Received WS Frame. Type is text
2018/09/21 15:48:22 [debug] [lua] ws-handler.lua:150: Received text data: [16,2,{},"com.myapp.hello",[0]]
2018/09/21 15:48:22 [debug] [lua] redis.lua:78: findPatternedUri(): Not found any prefix match
2018/09/21 15:48:22 [debug] [lua] ws-handler.lua:112: Received WS Frame. Type is nil
2018/09/21 15:48:22 [debug] [lua] ws-handler.lua:112: Received WS Frame. Type is pong
2018/09/21 15:48:22 [debug] [lua] ws-handler.lua:112: Received WS Frame. Type is nil
2018/09/21 15:48:22 [debug] [lua] ws-handler.lua:112: Received WS Frame. Type is pong
2018/09/21 15:48:22 [debug] [lua] ws-handler.lua:112: Received WS Frame. Type is nil
2018/09/21 15:48:22 [debug] [lua] ws-handler.lua:112: Received WS Frame. Type is pong
```

So, i think problem is on autobahn|python side. Can you examine it?

**Comment by haizaar** [comment] 2018-09-21 13:12
That's interesting, because autobahn is a reference implementation of WAMP client, de facto.
I'll try to raise loglevel on autobahn and see the client side of things. Then if you are right we'll file a bug :)

Can you please show me how do you raise wiola/lua to debug level? I've tried setting error_log to debug ([this line](https://gist.github.com/haizaar/208e4c63954db1cbc3aa1de4b8e5951f#file-nginx-conf-L3)) and it didn't help.

**Comment by KSDaemon** [comment] 2018-09-21 13:16
As i mention earlier — you also need to use wiola files from src/wiola/, because in luarocks package debug information is stripped out.

```
--volume $PWD/ws-handler.lua:/usr/local/openresty/luajit/share/lua/5.1/wiola/ws-handler.lua \
    --volume $PWD/wiola.lua:/usr/local/openresty/luajit/share/lua/5.1/wiola/wiola.lua \
```

**Comment by KSDaemon** [comment] 2018-09-21 13:29
Also, can you have a look into crossbar, because some my coworkers say that crossbar doesn't respond to `ping` websocket frames, and can only initiate `ping` frames by itself. 
So full picture is: crossbar initiates `ping` websocket requests only, and autobahn responds with `pong` answers only %)
But may be i'm missing something...

**Comment by haizaar** [comment] 2018-09-21 13:45
Thanks (I can't seem to find your previous answer on this).

I've added these lines at the top of client.py:
```
import logging
import txaio

logging.basicConfig(format="%(asctime)s.%(msecs)03d %(name)-15s %(levelname)-5s ##  %(message)s %(module)s.%(funcName)s:%(lineno)d")
txaio.start_logging(level='debug')
```
And here are the output: https://pastebin.com/qya1q9nv
The sample client works fine with crossbar.

I'm not sure what you are saying - do you think crossbar/autobahn violate WAMP/WebSocket protocol?

**Comment by haizaar** [comment] 2018-09-21 13:46
BTW, I've applied your suggestion for Wiola debugging - it works, but mine output looks a bit different from yours. Here is the snippet:

```
2018/09/21 13:30:35 [debug] 8#8: *13 [lua] wiola.lua:231: _putData(): Preparing data for client: �A��z�I��
2018/09/21 13:30:35 [debug] 8#8: *13 [lua] wiola.lua:233: _putData(): Pushed data for client into store
2018/09/21 13:30:35 [debug] 8#8: *13 [lua] wiola.lua:1237: receiveData(): Exiting receiveData()
2018/09/21 13:30:35 [debug] 8#8: *13 [lua] ws-handler.lua:91: Got data for client. DataType is binary. Sending...
2018/09/21 13:30:35 [debug] 8#8: *13 [lua] ws-handler.lua:154: Received binary data
2018/09/21 13:30:35 [debug] 8#8: *13 [lua] wiola.lua:584: receiveData(): Cli regId: 1.9453859655504e+15 Received data. WAMP msg Id: 16
2018/09/21 13:30:35 [debug] 8#8: *13 [lua] wiola.lua:171: _validateURI(): Validating URI: com.myapp.hello. Found match? true, error: nil
2018/09/21 13:30:35 [debug] 8#8: *13 [lua] wiola.lua:1237: receiveData(): Exiting receiveData()
2018/09/21 13:30:36 [debug] 8#8: *13 [lua] ws-handler.lua:154: Received binary data
2018/09/21 13:30:36 [debug] 8#8: *13 [lua] wiola.lua:584: receiveData(): Cli regId: 1.9453859655504e+15 Received data. WAMP msg Id: 16
2018/09/21 13:30:36 [debug] 8#8: *13 [lua] wiola.lua:171: _validateURI(): Validating URI: com.myapp.hello. Found match? true, error: nil
2018/09/21 13:30:36 [debug] 8#8: *13 [lua] wiola.lua:1237: receiveData(): Exiting receiveData()
2018/09/21 13:30:37 [debug] 8#8: *13 [lua] ws-handler.lua:154: Received binary data
2018/09/21 13:30:37 [debug] 8#8: *13 [lua] wiola.lua:584: receiveData(): Cli regId: 1.9453859655504e+15 Received data. WAMP msg Id: 16
```

**Comment by KSDaemon** [comment] 2018-09-21 15:29
Well, may be there are errors in lua-resty-websocket library i'm using...
Webscoket ping/pong — is rarely used or implemented feature.... So error can be in any module/library

**Comment by KSDaemon** [comment] 2019-02-15 10:10
As there is no new information, closing for now. Feel free to reopen.

**Closed by KSDaemon** 2019-02-15 10:10 UTC
